### ISSUE TITLE
postgresql@15 fails to start with `brew services` since last update

### ISSUE THREAD

**Issue by netmute** [Homebrew/homebrew-core#124214]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ $ brew config
HOMEBREW_VERSION: 4.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f
Last commit: 5 days ago
Core tap JSON: 25 Feb 12:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
~ $ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installed latest postgressql@15 update via `brew upgrade`, then started postgres with `brew services start postgresql@15`.

### What happened (include all command output)?

`brew services list` shows error status for postgres:
`postgresql@15 error  256 se   ~/Library/LaunchAgents/homebrew.mxcl.postgresql@15.plist`

Postgres logfile complains about wrong locales being set:
```
~ $ tail /opt/homebrew/var/log/postgresql@15.log
2023-02-25 13:58:46.866 CET [87981] FATAL:  postmaster became multithreaded during startup
2023-02-25 13:58:46.866 CET [87981] HINT:  Set the LC_ALL environment variable to a valid locale.
2023-02-25 13:58:46.867 CET [87981] LOG:  database system is shut down
```

Locales are set correctly, and postgres started fine before the update.

### What did you expect to happen?

Postgres to start.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql@15
brew services start postgresql@15

~ $ brew services list
Name          Status     User File    
postgresql@15 error  256 se   ~/Library/LaunchAgents/homebrew.mxcl.postgresql@15.plist
```

**Comment by netmute** [comment]
I've been digging around the other issues a bit, and this seems to be related to #123613.

**Comment by SMillerDev** [comment]
Could be that https://github.com/Homebrew/homebrew-core/pull/124135 caused this

**Comment by mikl** [comment]
Seeing this too.

As a workaround, you can run PostgreSQL directly on the command line with this command

```/opt/homebrew/opt/postgresql@15/bin/postgres -D /opt/homebrew/var/postgresql@15```

Note that this will run PostgreSQL in the foreground, so you’ll need to keep that terminal session opeas long as you want it to run.

**Comment by carlocab** [comment]
Seems to still be happening, based on feedback from https://github.com/Homebrew/homebrew-core/pull/124318.

**Comment by ZhongRuoyu** [comment]
Now with a `brew update && brew upgrade postgresql@15` this issue should be fixed.

**Comment by ZhongRuoyu** [comment]
> this resolution does not work ..

@yourssvk Can you try `brew restart postgresql@15`? Also, check if `realpath "$(brew --prefix postgresql@15)"` gives you a directory named `15.2_3`. If not, then you don't have the latest revision installed.

> the same problem with postgresql@14 as well..

You shouldn't be seeing this problem with `postgresql@14`; https://github.com/Homebrew/homebrew-core/pull/124252 is not merged. Can you share the output of `tail -n 20 "$(brew --prefix)/var/log/postgresql@14.log"`?

**Comment by yourssvk** [comment]
Postgressql 14 log tail (I am not running the command as root user):

`"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.`

Brew services list in both postgres 14 and 15:

`
brew services list
Name          Status       User File
postgresql@14 error  19968 root ~/Library/LaunchAgents/homebrew.mxcl.postgresql@14.plist
postgresql@15 error  19968 root ~/Library/LaunchAgents/homebrew.mxcl.postgresql@15.plist
`

realpath "$(brew --prefix postgresql@15)"

`
/usr/local/Cellar/postgresql@15/15.2_3
`

**Comment by gromgit** [comment]
> I am not running the command as root user

This output you posted:
```
Name          Status       User File
postgresql@14 error  19968 root ~/Library/LaunchAgents/homebrew.mxcl.postgresql@14.plist
postgresql@15 error  19968 root ~/Library/LaunchAgents/homebrew.mxcl.postgresql@15.plist
```
says you ran`sudo brew services list`, i.e. **as root**. The log output says you ran `sudo brew services start postgresql@14` at some point.

**Comment by geuis** [comment]
> says you ran`sudo brew services list`, i.e. **as root**. The log output says you ran `sudo brew services start postgresql@14` at some point.

I'm running into the same error with the identical error status:
```
postgresql@14 error  19968 root ~/Library/LaunchAgents/homebrew.mxcl.postgresql@14.plist
```
For me this is a clean installation. I removed and reinstalled postgresql@14 multiple times just to make sure I wasn't using `sudo` by mistake. The user still shows as `root`.

**Comment by yourssvk** [comment]
Same was the case with me

**Comment by wflanagan** [comment]
FYI, it's not unexpected that one would run it as root.. considering that's the instruction it gives you to see richer details when postgres doesn't start.

**Comment by wflanagan** [comment]
@gromgit I do not have this, and I have the same error. 

```
Name               Status     User            File
postgresql@15      error  256 williamflanagan ~/Library/LaunchAgents/homebrew.mxcl.postgresql@15.plist
redis              started    williamflanagan ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
```
