### ISSUE TITLE
gnutls 3.5.14 - Post Install Fails

### ISSUE THREAD

**Issue by nickv2002** [Homebrew/homebrew-core#15308]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Just running the regular update for gnutls
- What happened (include command output)
Post install script failed

```
==> Upgrading 1 outdated package, with result:
gnutls 3.5.14
==> Upgrading gnutls
==> Downloading https://homebrew.bintray.com/bottles/gnutls-3.5.14.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gnutls-3.5.14.sierra.bottle.tar.gz
==> Using the sandbox
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gnutls`
==> Summary
🍺  /usr/local/Cellar/gnutls/3.5.14: 1,105 files, 7.6MB
nick@HackMac:~$ brew postinstall gnutls
==> Using the sandbox
Error: undefined method `success?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:74:in `block in post_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:68:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:68:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1021:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:886:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1020:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
nick@HackMac:~$ brew gist-logs gnutls
Error: No logs.
nick@HackMac:~$ brew config
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 3 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9faad13b33e9f68346167d9d447d6141ec943934
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
nick@HackMac:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail
```

**Comment by DomT4** [comment]
> ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 3 months ago

That's your problem. Try:

```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update && brew postinstall gnutls
```

**Comment by nickv2002** [comment]
@DomT4 Thanks for your help, I wonder why that got stuck 3 months ago but I'm just seeing problems now.

Unfortunately your suggested solution fails on the `git fetch`:
```
nick@HackMac:/usr/local/Homebrew$ cd "$(brew --repo)" && git fetch
error: Could not read 48e8cf756853230934cf1b89a1adf85ea1310d62
error: Could not read 2631474f25fdd2b98d74946031e4baa6d451083c
error: Could not read 48e8cf756853230934cf1b89a1adf85ea1310d62
error: Could not read 2631474f25fdd2b98d74946031e4baa6d451083c
remote: Counting objects: 4504, done.
remote: Compressing objects: 100% (1254/1254), done.
remote: Total 4504 (delta 3406), reused 4185 (delta 3116), pack-reused 0
Receiving objects: 100% (4504/4504), 625.70 KiB | 0 bytes/s, done.
Resolving deltas:  97% (3321/3406), completed with 337 local objects.
fatal: pack has 85 unresolved deltas
fatal: index-pack failed
nick@HackMac:/usr/local/Homebrew$ echo $?
128
```
Should I go ahead and do the `git reset --hard origin/master` anyway?

**Comment by DomT4** [comment]
Possibly. Let's check `cd "$(brew --repo)" && git status` first to check you're not on a locally modified branch or something.

It doesn't make much sense for you to have managed to get stuck at that commit point, that's well after all the known update issues were resolved.

**Comment by nickv2002** [comment]
Nothing special about my local branch:
```
nick@HackMac:/usr/local/Homebrew$ cd "$(brew --repo)" && git status
On branch stable
nothing to commit, working tree clean
```
I haven't been messing with my homebrew install using anything other than the normal `brew` tools, but 3 months ago was about when I migrated to a new Mac so perhaps that contributed…?

**Comment by DomT4** [comment]
Yeah, go ahead and try the whole:

```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update && brew postinstall gnutls
```
command. If you haven't made any expected local changes there's nothing to lose by trying that, so.

**Comment by nickv2002** [comment]
Hmm, forced the `git reset --hard origin/master` step even after the `git fetch` failed but I'm still getting the same error when I try to `brew postinstall gnutls` and my `brew status` is still showing a commit 3 months ago.
```
nick@HackMac:/usr/local/Homebrew$ git reset --hard origin/master
HEAD is now at 8ea778f7c Merge pull request #2412 from EricFromCanada/master

nick@HackMac:/usr/local/Homebrew$ git status
On branch stable
nothing to commit, working tree clean

nick@HackMac:/usr/local/Homebrew$ brew config
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 3 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0ea49b9d4d8db004c28bd34ace0de4bd0f31de4f
Core tap last commit: 12 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11

nick@HackMac:/usr/local/Homebrew$ brew update
Already up-to-date.

nick@HackMac:/usr/local/Homebrew$ brew postinstall gnutls
==> Using the sandbox
Error: undefined method `success?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:74:in `block in post_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:68:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:68:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1021:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:886:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1020:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
```
I think I need to do a bigger reset somehow. Can I just delete/reinstall the homebrew binaries like so? 
```
rm -rf "$(brew --repo)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
Anything else I should check for bug reporting purposes before I do this?

**Comment by DomT4** [comment]
`$(brew --repo)` contains all of your taps as well, so if you've any custom taps installed you'll want to note those down so you can retap them afterwards. But yes, you should be fine doing it that way. I'm still fairly puzzled how you've ended up stuck where you are.

**Comment by nickv2002** [comment]
Yeah, this worked:
```
rm -rf "$(brew --repo)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
I moved my Taps out of `/usr/local/Homebrew/Library/Taps` and then back after running the install script.

My suspicion is that something got tweaked when I migrated to a new computer but that's just a guess.

Thanks so much for your help.
