### ISSUE TITLE
Octave requires jdk 6

### ISSUE THREAD

**Issue by romanbsd** [Homebrew/homebrew-core#16979]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
This is after I reinstalled it w/o java though.
https://gist.github.com/anonymous/78f4c5412d2c3c34b0bafd5ba2898abe
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgraded the octave to 4.2.1_5 by `brew upgrade`
- What happened (include command output)
"Install legacy java" MacOS helper was launched, proposing to install JDK 6.
- What you expected to happen
Octave prompt to appear
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install` on Sierra.
# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by ilovezfs** [comment]
@schoeps looks like it will need to be optional after all.

**Comment by schoeps** [comment]
that is a pity and possibly a bug in the dependency treatment? java 8 should do it!

**Comment by schoeps** [comment]
@romanbsd this needs to be fixed but on the other hand the java bindings are often quite useful! for example when dealing with xml files. Maybe you should give them a try.

**Comment by JCount** [comment]
It is a know octave bug, not something due to Homebrew's packaging.

**Comment by ilovezfs** [comment]
@schoeps apparently it may be this according to @iMichka: https://github.com/Homebrew/homebrew-science/issues/4643#issuecomment-323523584

**Comment by schoeps** [comment]
Ok! I thought homebrew was asking for java 1.6 as a dependency, but it's really octave itself that triggers the system. I will try to find out if this is really an octave bug as the other thread indicated that it is rather a java bug.

**Comment by schoeps** [comment]
however, for now making it optional should satisfy most people ... people that need java can recompile themselves.

**Comment by schoeps** [comment]
Can someone try https://gist.github.com/schoeps/2e81683de2f26065883383dec3b549aa? This should fix the java trouble. Also submitted upstream http://savannah.gnu.org/patch/index.php?9439.

**Comment by schoeps** [comment]
Octave should compile with both Java 1.8 and 1.9 (preview). If using 1.9 the old Apple Java is not necessary. On the other hand, if compiling with 1.8, then octave starts without java but requires installation of 1.6 on usage (this is probably due to the bug https://bugs.openjdk.java.net/browse/JDK-7131356).

**Comment by iMichka** [comment]
Not sure we should focus much on 1.9. Last time I saw something about it the release cycle was postponed again due to the jigsaw disaster. I think the last date has been put somewhere for end of september, but not sure. Surprises may still happen :)

**Comment by schoeps** [comment]
@iMichka agreed. However, the fix (7131356) will hopefully also come to 1.8.x and it's good to know that octave will work with future java releases.
