### ISSUE TITLE
Install homebrew failure on mac os 10.13.3 beta

### ISSUE THREAD

**Issue by tdenley1** [Homebrew/homebrew-core#21734]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I am trying to install homebrew, yet terminal reports failure as shown below. Please assist. Thank you.
Last login: Thu Dec 14 14:34:39 on ttys000
t-ds-iMac:~ tden$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/bin
/usr/local/etc
/usr/local/include
/usr/local/lib
/usr/local/opt
/usr/local/sbin
/usr/local/share
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var
==> The Xcode Command Line Tools will be installed.

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local
Password:
mkdir: /usr/local: Operation not permitted
Failed during: /usr/bin/sudo /bin/mkdir -p /usr/local
t-ds-iMac:~ tden$

**Comment by fxcoudert** [comment]
- Can you tell us what permissions your `/usr` and `/usr/local` directories have? Run `ls -ld /usr` and `ls -l /usr`.
- Consider [fixing the permissions for your hard drive](https://support.apple.com/en-us/HT201560) and retrying to install.

**Comment by tdenley1** [comment]
I repaired permissions on hard drive using RepairPermissions V3, followed by a restart, retrying to install, which resulted in failure, again with same terminal message. The terminal output of permissions you requested is shown below. Any further suggestions? Thanks in advance.
Last login: Fri Dec 15 10:09:59 on ttys000
t-ds-iMac:~ tden$ ls -ld /usr
drwxr-xr-x@ 11 root  wheel  374 Dec 13 18:21 /usr
t-ds-iMac:~ tden$ ls -l /usr
total 16
lrwxr-xr-x    1 root  wheel      8 Aug 10 18:47 X11 -> /opt/X11
lrwxr-xr-x    1 root  wheel      8 Aug 10 18:47 X11R6 -> /opt/X11
drwxr-xr-x  976 root  wheel  33184 Dec 14 11:29 bin
drwxr-xr-x  263 root  wheel   8942 Dec 14 11:50 include
drwxr-xr-x  311 root  wheel  10574 Dec 14 11:50 lib
drwxr-xr-x  234 root  wheel   7956 Dec 14 11:29 libexec
drwxr-xr-x  247 root  wheel   8398 Dec 12 17:12 sbin
drwxr-xr-x   46 root  wheel   1564 Dec 13 18:21 share
drwxr-xr-x    5 root  wheel    170 Jul  7 02:00 standalone
t-ds-iMac:~ tden$

**Comment by fxcoudert** [comment]
You don't already have a `/usr/local`, although it should have been created during installation of macOS (or conserved by migration from earlier macOS version). And system integrity protection is not allowing you to create it, even with admin privileges. This was a problem in previous macOS releases (around El Capitan, IIRC), but it was fixed then.

Please report this to Apple as a bug in the macOS 10.13.3 beta. `/usr/local` should be re-creatable by the user if somehow it disappeared. (And please keep us informed of their response, as it is going to affect Homebrew in a major way unless it is fixed!)

**Comment by ilovezfs** [comment]
>This was a problem in previous macOS releases (around El Capitan, IIRC), but it was fixed then.

It was changed again in 10.13 such that /usr/local to be removed nor able to be created when SIP is enabled. So yes if /usr/local has gone missing that is a major bug.

**Comment by ilovezfs** [comment]
I'm going to assume this will work itself out.

**Comment by shanawarkhan** [comment]
Hey, I'm still facing this issue in installing homebrew which is such a disappointment. 
Has there been any solution for it yet?
