### ISSUE TITLE
Neo4J formula uses wrong path for service

### ISSUE THREAD

**Issue by jschank** [Homebrew/homebrew-core#38585]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I did - but I needed to create an access token and I'm not sure I did it right.

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

$ brew config
HOMEBREW_VERSION: 2.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 649d1427f5fe41323c436608f5c21513f8f34f71
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4516ee029aac77079a6b1368d8d5402ed573a94b
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.GafMjk5uNS/org.macosforge.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/jschank/Library/Logs/Homebrew
HOMEBREW_VISUAL: /usr/local/bin/code -w -n
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12, 1.8.0_202
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: 10.2
CLT headers: 10.2.0.0.1.1552586384
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.

To help us debug your issue please explain:

- What you were trying to do (and why)
I was trying to install neo4j with home brew. And I was attempting to start the service with 
$ brew services start neo4j

- What happened (include command output)
The response indicated that the service was running. However the color was different than other services... What I mean is, running 
$ brew services list
shows me 3 running services: mysql, mosquitto, and neo4j. The first two were clearly green, but neo4j was more yellow (even though it said started)

- What you expected to happen
I expected to be able to browse to http://localhost:7474 and see neo4j stuff.
But the page could not load.

- Step-by-step reproduction instructions (by running `brew install` commands)

I dug into the problem, and I think...
That the service is looking to run
/usr/local/opt/neo4j/bin/neo4j console

But there was no symlink there. So I created one.
And then the service worked.

When I ran $ brew doctor, to create this issue, it told me I had unlinked kegs. I followed the advice and brew created 4 symlinks. 

(Possibly the brew link command would have fixed the problem, but possibly the symlinks could not have been created until I did the manual symlink)

**Comment by SMillerDev** [comment]
Was any of the unlinked kegs neo4j?

**Comment by jschank** [comment]
It was. But i suspect it only saw the binaries to symlink because of the opt symlink i created. On the other hand, the offer to link might have been the necessary fix. Based on order of steps i ended up going through, i just don’t know.

When i install neo on my desktop system. I will pay closer attention. 

I thought i fixed it. But maybe homebrew would have fixed itself. With the $ brew doctor advice.

**Comment by SMillerDev** [comment]
The way homebrew knows what symlinks to create would mean brew doctor suggestions would fix it.
This is why  "ran brew doctor, fixed all issues and can still reproduce the problem" is in the issue template.
