### ISSUE TITLE
parallelstl: install CMake config files

### ISSUE THREAD

**Issue by omor1** [Homebrew/homebrew-core#53751]
## Checklist

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
The parallelstl formula doesn't use CMake to generate and install the ParallelSTLConfig.cmake file. This makes using the Parallel STL library more difficult than it ought to be.

## What happened (include command output)
Parallel STL is missing the CMake config file after installation via brew.

## What you expected to happen
Installing Parallel STL would fully install Parallel STL.

**Comment by omor1** [comment]
`brew doctor` tells me that the command line tools are supposedly out-of-date; System Preferences does not show me an update. This prevents me from running `brew gist-logs`. In any case, this is very obviously a problem with the formula, given that it doesn't generate a bottle.

**Comment by Bo98** [comment]
Should be fixed now.

**Comment by omor1** [comment]
You forgot to bump the revision!

**Comment by Bo98** [comment]
Indeed - I'll go bump it. You can do `brew reinstall parallelstl` in the meantime.

**Comment by omor1** [comment]
I've already done that :). Thanks!

**Comment by omor1** [comment]
Using `pstl::ParallelSTL` from CMake seems to be problematic in the current setup. The replacement STL headers are installed in the non-standard `stdlib` directory inside the parallelstl Cellar directory, but this isn't linked into `/usr/local/stdlib`. It seems that `ParallelSTLTargets.cmake` finds the install directory based on `${CMAKE_CURRENT_LIST_FILE}`, which I guess doesn't resolve the symbolic link to the Cellar directory, so it tries to find `stdlib` in `/usr/local` rather than in `/usr/local/Cellar/parallelstl/20200330`.

I'm not sure what the solution here is. Installing the `stdlib` directory is inelegant, but should work.

**Comment by Bo98** [comment]
Upstream's CMake files don't even install `stdlib` by default. I had to do that bit manually. And since it isn't in a standard Unix location - it doesn't get symlinked to `/usr/local`. (You can find it in `/usr/local/opt/parallelstl/stdlib`, but that probably doesn't help you.) There is strict enforcements on what gets symlinked to `/usr/local`.

I think the solution would be for it to be in a standard location, such as `lib/parallelstl/stdlib` or maybe even something in `share`. I suspect upstream don't give that flexibility though - it isn't even installed by default.

**Comment by omor1** [comment]
I'm as flummoxed as you are. The separation of the replacement STL files into `stdlib` only happened with the last two releases. Maybe installing it into `/usr/local/Cellar/parallelstl/<version>/include/pstl/stdlib`? That would likely require a patch to CMakeLists to change the include directory `INSTALL_INTERFACE`. Mostly it seems that upstream is problematic for this.

**Comment by Bo98** [comment]
I could mess around with patching the CMakeLists but I'd like it to not be something that sticks around forever. I would be worth making a bug report upstream first and see if there's any initial thoughts there.

**Comment by omor1** [comment]
I'm working on that right now.

**Comment by omor1** [comment]
For now I'm working around this by using `-DParallelSTL_ROOT=/usr/local/opt/parallelstl` when configuring CMake.

**Comment by omor1** [comment]
In the meantime, should we open this issue back up?

**Comment by Bo98** [comment]
We generally don't for upstream issues but I'll still be receiving notifications for this issue and may re-open when there's action to be done on our side.

If you need any further evidence for upstream, vcpkg were also forced to have to patch upstream's scripts to actually install `stdlib` and to do so in a standard location `include/pstl`: https://github.com/microsoft/vcpkg/blob/master/ports/parallelstl/fix-cmakelist.patch

**Comment by omor1** [comment]
That's a good catch, I'll make note of it on https://github.com/intel/parallelstl/issues/33.

**Comment by Bo98** [comment]
Yeah, it's good to have other package managers to compare to - I didn't want them to get all caught up in the Homebrew symlink stuff.

I'm pretty sure Debian (if they were to have `parallelstl`) would also reject anything that looked in `/usr/local` outside of standard locations, and would also likely raise a bug report if the install script didn't actually install everything.
