### ISSUE TITLE
`pass` (and other `gpg` dependents) cannot be installed if `gpg-suite` is present

### ISSUE THREAD

**Issue by lukasbestle** [Homebrew/homebrew-core#74447]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
HOMEBREW_VERSION: 3.0.10-182-gbd4c37b
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd4c37bfda487adc65f8bfdbad820a0a5fb38888
Last commit: 68 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4068106c23f83789b8ec3c288ff6254b3229d69f
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano -w
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  php-version
  qdated

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php
  gnupg
```

### 

The `brew doctor` above contains no "Warning" lines that are related to this issue.

### What were you trying to do (and why)?

Install the `pass` formula because I want to use `pass` on my machine

### What happened (include all command output)?

Homebrew tried to install and link `gpg` even though GPG was already installed at `/usr/local/bin/gpg` by the `gpg-suite` cask:

```
==> Downloading https://homebrew.bintray.com/bottles/gnupg-2.2.27.catalina.bottle.tar.gz
Already downloaded: /Users/lux/Library/Caches/Homebrew/downloads/b8ddce097cd8556c77809f778078f497c0ba9231b05fce4f04bd4a4772881eae--gnupg-2.2.27.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/pass-1.7.3.catalina.bottle.2.tar.gz
Already downloaded: /Users/lux/Library/Caches/Homebrew/downloads/7588e0726ec2d1f78e78006e58becd61316427dbfe99b99df9c56e8821afb499--pass-1.7.3.catalina.bottle.2.tar.gz
==> Installing dependencies for pass: gnupg
==> Installing pass dependency: gnupg
==> Pouring gnupg-2.2.27.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/gpg
Target /usr/local/bin/gpg
already exists. You may want to remove it:
  rm '/usr/local/bin/gpg'

To force the link and overwrite all conflicting files:
  brew link --overwrite gnupg

To list all files that would be deleted:
  brew link --overwrite --dry-run gnupg

Possible conflicting files are:
/usr/local/bin/gpg -> /usr/local/MacGPG2/bin/gpg2
==> Summary
🍺  /usr/local/Cellar/gnupg/2.2.27: 140 files, 11.9MB
==> Installing pass
==> Pouring pass-1.7.3.catalina.bottle.2.tar.gz
==> Caveats
fish completions have been installed to:
  /usr/local/share/fish/vendor_completions.d
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/pass
==> Summary
🍺  /usr/local/Cellar/pass/1.7.3: 34 files, 148.9KB
==> Caveats
==> pass
fish completions have been installed to:
  /usr/local/share/fish/vendor_completions.d
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/pass
```

### What did you expect to happen?

Homebrew should either skip installing `gpg` entirely (preferred) or `gpg` should be keg-only if `gpg-suite` is already installed. As `pass` does not rely on anything specific about the `gpg` formula, `gpg-suite` works just fine with it.

See the previous discussion in https://github.com/Homebrew/brew/issues/11011.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --cask gpg-suite
brew install pass
```

**Comment by SMillerDev** [comment]
We don't control what casks install. If they install in the same directory as homebrew there is nothing we can do about that.

**Comment by lukasbestle** [comment]
You are right that Homebrew cannot determine automatically if an installed cask conflicts with a formula – casks can install files anywhere on the system.

However in this particular case we know that the `gpg-suite` cask conflicts with the `gpg` formula. So we can fix the issue by updating the `gpg` formula configuration to check for the existence of the `gpg-suite` cask.

Please reopen this issue as the problem is not yet solved.

Pinging @carlocab and @MikeMcQuaid, who were part of the original discussion.

**Comment by SMillerDev** [comment]
We're not adjusting homebrew Formulae to adjust for upstream package behavior. As far as I know we never have and we probably never will. The best way to resolve this is to ask upstream to stop using conflicting binary names (unlikely in this case) or to keep the formula unlinked for yourself.

**Comment by lukasbestle** [comment]
I wouldn't say this is upstream package behavior. The `gpg` formula and the `gpg-suite` cask are both part of the same Homebrew universe and their behavior is known. If `gpg-suite` was a formula, we would solve this with `conflicts_with`.

The issue with keeping the formula unliked for myself is that it's not possible to automate this. If I install `pass` using an automation tool like Ansible (which I do), Homebrew will exit with exit code 1 because it couldn't link `gpg`. Automation tools will treat this as overall failure.

**Comment by carlocab** [comment]
> Homebrew should either skip installing `gpg` entirely (preferred)

As mentioned previously, we used to do this for other formulae, and it led to a lot of problems. It may well be that `pass` is an exception, but we just don't have the resources to keep verifying that this is the case when updates are made to `pass`, `gnupg`, or `gpg-suite`.

> or `gpg` should be keg-only if `gpg-suite` is already installed.

That's already effectively what you have here. To make sure, you can do `brew unlink gnupg`. I really don't think silently making `gnupg` keg-only when `gpg-suite` is installed is a good idea: other users might find this behaviour unexpected, and it could break other formulae that depend on `gnupg`. Perhaps you don't use other formulae that depend on `gnupg`, but other users might.

I'm not sure what you hoped to achieve by pinging `@MikeMcquaid` and I here, but doing so is really not okay.

**Comment by lukasbestle** [comment]
> That's already effectively what you have here.

Unfortunately not. As I wrote above, `brew` exits with exit code 1, which breaks automation setups.

I understand the downsides of the solutions we are discussing here. But this problem still exists and is unsolved, so I think we should keep this issue open until it is solved, potentially by finding a different solution that doesn't have these downsides.

Or as you wrote it in the other issue: "Open issues on our issue tracker represent work to be done."

> I'm not sure what you hoped to achieve by pinging `@MikeMcquaid` and I here, but doing so is really not okay.

It's simple: @MikeMcQuaid has suggested these solutions in https://github.com/Homebrew/brew/issues/11011#issuecomment-812685023.

Also: You and him were already involved in this discussion, so it's most efficient and best for the solution of this problem if *you* add your thoughts to this. Other team members of the Homebrew team would have to read into the issue from the start.

Can you explain why "doing so is really not okay" from your point of view?

**Comment by SMillerDev** [comment]
> However in this particular case we know that the gpg-suite cask conflicts with the gpg formula. So we can fix the issue by updating the gpg formula configuration to check for the existence of the gpg-suite cask.

https://github.com/Homebrew/homebrew-cask/pull/103028/files should resolve this by making the cask conflict as it should.

**Comment by lukasbestle** [comment]
@SMillerDev Thanks for creating the PR! Does this work in the other direction as well, meaning that if `gpg-suite` is already installed, it will block the installation of `gpg`? Or does it just prevent the installation of `gpg-suite` if `gpg` is installed?

**Comment by SMillerDev** [comment]
No, it only works one way. But formulae never define conflicts with casks (since we don't control the install there). I'd recommend moving the cask install steps in ansible after the formula install and that should make sure you always see the error.

**Comment by lukasbestle** [comment]
I see. But then this unfortunately doesn't fix this issue:

If my Ansible configuration contains tasks to install the `pass` formula and the `gpg-suite` cask, the `gpg-suite` cask installation would now fail even though I expect both to work together. I don't actually want *more* errors, I want *less* errors. :)

**Comment by SMillerDev** [comment]
They don't work together though, no matter what you expect. They install the same thing so they conflict and brew just didn't define that correctly before.

**Comment by lukasbestle** [comment]
They do work together very well! `pass` is just a shell script that uses `gpg`, so it doesn't care at all whether it's using `gpg` or `gpg-suite`.

The issue is just that Homebrew installs the `gpg` formula even though I already have `gpg-suite` installed. As Carlo wrote above, this is difficult to get right, but it's an issue nonetheless.

Maybe we can solve this from a different direction: Is it possible to tell Homebrew to ignore a specific dependency? Then I could so something like this:

```sh
brew install --ignore-gpg pass
```

and it would be my responsibility as the user to verify that everything works as expected.

**Comment by SMillerDev** [comment]
> They do work together very well! pass is just a shell script that uses gpg, so it doesn't care at all whether it's using gpg or gpg-suite.

But homebrew does since we don't test our formulae with switched out dependencies. You can maintain a separate pass version in a tap and make it depend on the cask instead of the formulae, but homebrew/core is meant to work completely independently of homebrew/cask.

In the end the thing you want (defining your own dependencies for a formulae) simply isn't supported by brew.

**Comment by lukasbestle** [comment]
I understand that. What about my question/suggestion to ignore a specific dependency at install time using a flag?

**Comment by carlocab** [comment]
> Unfortunately not. As I wrote above, `brew` exits with exit code 1, which breaks automation setups.

Then wrap `brew` in a script that intercepts failures that you expect.

I don't use `ansible`, but I'd guess that it provides you with a way to recover from expected failures in automation. You should use that. If it doesn't, you should open a pull request there that allows you to.

> Or as you wrote it in the other issue: "Open issues on our issue tracker represent work to be done."

Yes. And there's no work to be done here.

> Also: You and him were already involved in this discussion, so it's most efficient and best for the solution of this problem if _you_ add your thoughts to this. Other team members of the Homebrew team would have to read into the issue from the start.

No, it's most efficient if _you_ solved your _localised_ issues on your own. Maintainers just don't have the time to invest in fixing issues that affect individual users. If it starts affecting a number of users, then we can take a look.

> Can you explain why "doing so is really not okay" from your point of view?

Because it makes implicit demands on our time when there shouldn't be any, especially not for an issue that doesn't affect many users.

**Comment by MikeMcQuaid** [comment]
> No, it's most efficient if _you_ solved your _localised_ issues on your own. Maintainers just don't have the time to invest in fixing issues that affect individual users. If it starts affecting a number of users, then we can take a look.
> Because it makes implicit demands on our time when there shouldn't be any, especially not for an issue that doesn't affect many users.

👍🏻 

> I understand that. What about my question/suggestion to ignore a specific dependency at install time using a flag?

We're not going to do this, sorry. It's too likely to break things in the vast majority of cases.

> [Homebrew/homebrew-cask#103028](https://github.com/Homebrew/homebrew-cask/pull/103028) should resolve this by making the cask conflict as it should.

Thanks @SMillerDev!

---

Then only solution I could see here is a way for either the formula or the cask to not install the same symlink if they are both installed (or going to be installed) or allow symlinks (not binaries) from one to overwrite the other.

This would require additional code in Homebrew/brew to handle these cases and agreement between formulae and cask maintainers that this is the right solution for the problem.

This is not something I see me or other maintainers working on in the near future.
